### ISSUE TITLE
It doesn't work when using bower

### ISSUE THREAD

**Issue by cmartin81** [Textalk/tx-tinymce#4]
Hi,
I'm trying to get you plugin to work with bower. The problem is that the theme url and skin url are pointing to an invalid address.
It points to this directory 'tx-tinymce' instead of tinymce directory.

Here is the console log:
 GET http://localhost:3000/bower_components/tx-tinymce/themes/modern/theme.js --> invalid address.
I also get this error:
 TypeError: Cannot read property 'body' of undefined
    at Object.Editor.getBody (tinymce.min.js:30090)
    at Object.Editor.getContent (tinymce.min.js:29936)

**Comment by Dervisevic** [comment]
Haven't really looked at it just wanna say the cannot read body error is annoying but doesn't actually affect anything. Thanks for reporting the issue, we'll look into it.

**Comment by cmartin81** [comment]
Thanks for a quick reply.
When I copied the your project (ths js file) into tinymce everything worked. But I cannot do this because it is auto generated by bower.

**Comment by Dervisevic** [comment]
If you have the solution you could make a quick Pull request and i'd ship a new version for bower.

**Comment by cmartin81** [comment]
Sorry I don't have the solution :(

**Comment by Dervisevic** [comment]
Ok so the thing is, tinymce does the loading of the theme itself, we can't actually affect that from our code. Why we haven't noticed it is that we load a theme before loading tx-tinymce hence it doesn't try to go out and find it itself. So unfortunately we can't do anything about it except update the README to indicate that this should be done.

**Comment by ssuryar** [comment]
Solution 1:
Add the below code - tx-tinymce.js
tinyMCE.baseURL = '/bower_components/tinymce/';

Solution 2:
Copy two folders skins & themes to tx-tinymce folder. U can copy folders from tinymce folder if exists or download from angular tinymce.
bower_components\tx-tinymce
